/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background:"#faf8ff",
        error:"#ba1a1a",
        error_container:"#ffdad6",
        inverse_on_surface:"#eef0ff",
        inverse_primary:"#c3c0ff",
        inverse_surface:"#283044",
        on_background:"#131b2e",
        on_error:"#ffffff",
        on_error_container:"#93000a",
        on_primary:"#ffffff",
        on_primary_container:"#dbd7ff",
        on_primary_fixed:"#100069",
        on_primary_fixed_variant:"#372abf",
        on_secondary:"#ffffff",
        on_secondary_container:"#54647a",
        on_secondary_fixed:"#0b1c30",
        on_secondary_fixed_variant:"#38485d",
        on_surface:"#131b2e",
        on_surface_variant:"#464555",
        on_tertiary:"#ffffff",
        on_tertiary_container:"#e4d4ff",
        on_tertiary_fixed:"#25005a",
        on_tertiary_fixed_variant:"#5a00c6",
        outline:"#777587",
        outline_variant:"#c7c4d8",
        primary:"#392cc1",
        primary_container:"#534ad9",
        primary_fixed:"#e3dfff",
        primary_fixed_dim:"#c3c0ff",
        secondary:"#505f76",
        secondary_container:"#d0e1fb",
        secondary_fixed:"#d3e4fe",
        secondary_fixed_dim:"#b7c8e1",
        surface:"#faf8ff",
        surface_bright:"#faf8ff",
        surface_container:"#eaedff",
        surface_container_high:"#e2e7ff",
        surface_container_highest:"#dae2fd",
        surface_container_low:"#f2f3ff",
        surface_container_lowest:"#ffffff",
        surface_dim:"#d2d9f4",
        surface_tint:"#5148d7",
        surface_variant:"#dae2fd",
        tertiary:"#5c00ca",
        tertiary_container:"#7531e6",
        tertiary_fixed:"#eaddff",
        tertiary_fixed_dim:"#d2bbff"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Manrope', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
